### PR TITLE
fix: ensure video source is set before resuming

### LINKED ISSUE #113: `recorder` in `create.tsx` may become `null` without notifying the user
after 1 and half our the ts got the value for null

https://github.com/user-attachments/assets/dc11a166-02f3-49d2-854d-0baae66d15c9

### PR DESCRIPTION
**Pull request by Efe-Cal**
I figured that when you want resume a timelapse, you can close the dialog without actually setting the the video source by the model close button.  Same issue applies when you want to update the video source, but it becomes destructive with Resume because then the `onCreate` function never gets called, leaving recorder `null` .

I simply added a case where you cannot close the model when the video source is not set.

There might be other issues that cause recorder to be null, but this probably fixes #113

### CODE REVIEW

File: apps/web/src/pages/timelapse/create.tsx [hunk 1]
```diff
@@ -310,6 +312,24 @@ export default function Page() {
       }
     }
 
+    function setStreamStoppedAlert(stream: MediaStream) {
```
Comment (ascpixi) [inline apps/web/src/pages/timelapse/create.tsx]: I'd rename this function, as `set<...>` functions are usually associated with state variables. A call to this function might be misinterpreted as setting a variable defined with `useState`.

**Review by ascpixi — CHANGES_REQUESTED** [review]
Oops, looks like we had some code style changes... ^^'>

**Comment by Efe-Cal** [comment]
@ascpixi is there a specific style guide you use? I use the editor default (it auto-formats), and tbh I think indentation in ternary may be correct-er (or at least chatgpt convinced me it is).
